# Welcome to BowDrops!
# Written by BowFun

# What should the plugin's message prefix be?
Prefix: "&7[&3Bow&eDrops&7]"

# How long (in minutes) should people with bowdrops.earlynotify get notified before a chest drop?
# This will delay the chest drop by the time specified.
# Be aware that a server restart will break the timer, causing the chest to not drop.
# Set to 0 to disable.
EarlyNotifyAndDelay: 10

# How long should a chest drop be active for (in hours)?
# Be aware that a server restart will break this timer, causing the chest to not expire.
# Set to 0 to disable.
ActiveTime: 3

# Should a chest launch a firework when it drops?
DroppedFirework: true
